version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobnest
      POSTGRES_USER: ranjit
      POSTGRES_PASSWORD: ranjit123
    ports:
      - "5432:5432"